apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/5 * * * *"   # run every 5 mins in dev for testing
    target:
      kind: CronJob
      name: governance-job